esend/Controllers/ParcelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace esend.Controllers
{
    [Route("[controller]/[action]")]
    public class ParcelController : Controller
    {
        private readonly ILogger _logger;

        private const string AuthenicatorUriFormat = "otpauth://totp/{0}:{1}?secret={2}&issuer={0}&digits=6";

        public ParcelController(
            ILogger<ManageController> logger)
        {
            _logger = logger;
        }

        public IActionResult GetParcelHistory(string trackNumber)
        {
            return View();
        }
    }
}

esend/Views/Shared/_Layout.cshtml
@using esend.Extensions
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - e-send</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="css/shipping/css/styles.op-shipping.css">
        <link rel="stylesheet" href="css/custom.css">
        <link rel="stylesheet" href="vendor/icon-line/css/simple-line-icons.css">
        <link rel="stylesheet" href="vendor/icon-line-pro/style.css">
        <link rel="stylesheet" href="vendor/icon-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="vendor/icon-hs/style.css">
        <link rel="stylesheet" href="vendor/hamburgers/hamburgers.min.css">
        <link rel="stylesheet" href="vendor/chosen/chosen.css">
        <link rel="stylesheet" href="vendor/slick-carousel/slick/slick.css">
        <link rel="stylesheet" href="vendor/cubeportfolio-full/cubeportfolio/css/cubeportfolio.min.css">
        <link rel="stylesheet" href="css/pluggins/magicSuggest/magicsuggest.css">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @if (HtmlExtensions.ShowMainNavigation(HttpContextAccessor.HttpContext.Request.Path))
    {
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">esend</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    }

    @RenderBody()

    <footer class="text-center text-md-left g-color-gray-dark-v4 g-bg-gray-dark-v2 g-py-25" style="background: black">
        <div class="container">
            <div class="row">
                <div class="col-md-6 d-flex align-items-center g-mb-10 g-mb-0--md">
                    <p class="w-100 g-color-gray-light-v8 mb-0">
                        © 2017 All right reserved. Development by e-send Team
                    </p>
                </div>
                <div class="col-md-6">
                    <ul class="list-inline float-md-right mb-0">
                        <li class="list-inline-item g-mr-10">
                            <a class="u-icon-v3 g-width-28 g-height-28 g-font-size-14 g-color-gray-light-v9 g-color-white--hover g-brd-gray-dark-v2 g-bg-gray-dark-v2 g-bg-primary--hover g-rounded-4 g-transition-0_2 g-transition--ease-in" href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li class="list-inline-item g-mr-10">
                            <a class="u-icon-v3 g-width-28 g-height-28 g-font-size-14 g-color-gray-light-v9 g-color-white--hover g-brd-gray-dark-v2 g-bg-gray-dark-v2 g-bg-primary--hover g-rounded-4 g-transition-0_2 g-transition--ease-in" href="#"><i class="fa fa-pinterest"></i></a>
                        </li>
                        <li class="list-inline-item g-mr-10">
                            <a class="u-icon-v3 g-width-28 g-height-28 g-font-size-14 g-color-gray-light-v9 g-color-white--hover g-brd-gray-dark-v2 g-bg-gray-dark-v2 g-bg-primary--hover g-rounded-4 g-transition-0_2 g-transition--ease-in" href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a class="u-icon-v3 g-width-28 g-height-28 g-font-size-14 g-color-gray-light-v9 g-color-white--hover g-brd-gray-dark-v2 g-bg-gray-dark-v2 g-bg-primary--hover g-rounded-4 g-transition-0_2 g-transition--ease-in" href="#"><i class="fa fa-instagram"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a class="u-icon-v3 g-width-28 g-height-28 g-font-size-14 g-color-gray-light-v9 g-color-white--hover g-brd-gray-dark-v2 g-bg-gray-dark-v2 g-bg-primary--hover g-rounded-4 g-transition-0_2 g-transition--ease-in" href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

<environment include="Development">
    @if (HtmlExtensions.ShowMainNavigation(HttpContextAccessor.HttpContext.Request.Path))
    {
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    }
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.j‌​s"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/js/app/esend.js"></script>
    
</environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

esend/Views/Shared/_TrackParcelPartial.cshtml
<form asp-area="" asp-controller="Parcel" asp-action="GetParcelHistory" method="post" id="trackParcelForm">       
    <div class="row">
        <div class="col-md-4">
            Enter Your P2G Reference Number:
        </div>
        <div class="col-md-4">
            <input id="trackNumber" name="trackNumber" class="form-control g-theme-color-gray-light-v10 g-placeholder-inherit g-brd-gray-light-v5 g-bg-gray-light-v5 g-bg-gray-light-v5--focus g-px-10 g-py-12" type="text" placeholder="e.g. P2G123456789">
        </div>
        <div class="col-md-4">
            <button class="btn btn-primary" type="submit">
                <i class="fa fa-search"></i> Track This Parcel
            </button>
        </div>
    </div>
</form>

<!-- Modal -->
<div class="modal fade" id="parcelHistoryDialog" role="dialog">
    <div class="modal-dialog">
    
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">
                <p>Some text in the modal.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
      
    </div>
</div>